config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    post 'associate_inventory', on: :member
  end

  resources :recipe_foods, only: [:index, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  root to: 'foods#index'
  get '/missing_foods', to: 'foods#missing_foods'
  get '/foods', to: 'foods#index', as: 'foods'

  get '/foods/:id', to: 'foods#show', as: 'food'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  get '/public_recipes', to: 'recipes#public_list', as: 'public_recipes'
  get '/GeneralShoppingList', to: 'general_shopping_list#index', as: 'general_shopping_list'

  resources :foods, except: [:index] do
    collection do
      get 'missing_foods'
    end
  end

  resources :inventories do
    resources :inventory_foods, only: [:index, :new, :create, :show, :update, :destroy]
  end  
end

app/models/inventory_food.rb
# app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory, foreign_key: 'inventory_id'
  belongs_to :food, foreign_key: 'food_id'
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  before_action :set_inventory
  before_action :set_inventory_food, only: %i[update destroy]

  def index
    @inventory_foods = @inventory.inventory_foods
  end

  def new
    @inventory_food = @inventory.inventory_foods.build
  end

  def create
    @inventory_food = @inventory.inventory_foods.build(inventory_food_params)

    if @inventory_food.save
      redirect_to inventory_inventory_foods_path(@inventory), notice: 'Inventory Food was successfully created.'
    else
      render :new
    end
  end

  def update
    if @inventory_food.update(inventory_food_params)
      redirect_to inventory_inventory_foods_path(@inventory), notice: 'Inventory Food was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @inventory_food.destroy
    redirect_to inventory_inventory_foods_path(@inventory), notice: 'Inventory Food was successfully removed.'
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:inventory_id])
  end

  def set_inventory_food
    @inventory_food = @inventory.inventory_foods.find(params[:id])
  end

  def inventory_food_params
    params.require(:inventory_food).permit(:quantity, :food_id)
  end
end

app/views/inventory_foods/index.html.erb
<div class="container">
<div class="center">

<div class="head-section">
<h1>Inventory Foods</h1>
<%= link_to 'View Inventory Shopping List', inventory_path(@inventory) if @inventory %>
<%= link_to 'Add Food To Inventory' , new_inventory_inventory_food_path(@inventory) %>
<%= link_to 'Back', inventories_path %>
</div>

<table class="table">
  <thead >
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_foods.each do |inventory_food| %>
      <tr>
        <td><%= inventory_food.food.name %></td>
        <td><%= inventory_food.quantity %></td>
      <td>  <%= link_to 'Remove item', inventory_inventory_food_path(@inventory, inventory_food), method: :delete, data: { confirm: 'Are you sure you want to remove this item?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/inventory_foods/new.html.erb
<div class="container" >
<div class="center" >

<h1 class="notice">Inventory Foods</h1>

<div class="Iform" >
<%= form_for [@inventory, InventoryFood.new] do |f| %>
  <div class="field">
    <%= f.label :foods_id, 'Food' %>
    <%= f.collection_select(:food_id, Food.all, :id, :name, prompt: 'Select a food') %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div>
    <%= f.submit 'Add Inventory Food' %>
  </div>
<% end %>
</div>

</div>
</div>

app/views/inventory_foods/show.html.erb
<!-- app/views/inventory_foods/index.html.erb -->

<h1>InventoryFoods</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Inventory ID</th>
      <th>Food ID</th>
      <!-- Add more columns as needed -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_foods.each do |inventory_food| %>
      <tr>
        <td><%= inventory_food.quantity %></td>
        <td><%= inventory_food.inventory_id %></td>
        <td><%= inventory_food.food_id %></td>
        <!-- Add more cells for additional attributes -->
        <td><%= link_to 'Show', inventory_food %></td>
        <td><%= link_to 'Edit', edit_inventory_food_path(inventory_food) %></td>
        <td><%= link_to 'Destroy', inventory_food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New InventoryFood', new_inventory_food_path %>