config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    post 'associate_inventory', on: :member
  end

  resources :recipe_foods, only: [:index, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  root to: 'foods#index'
  get '/missing_foods', to: 'foods#missing_foods'
  get '/foods', to: 'foods#index', as: 'foods'

  get '/foods/:id', to: 'foods#show', as: 'food'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  get '/public_recipes', to: 'recipes#public_list', as: 'public_recipes'
  get '/GeneralShoppingList', to: 'general_shopping_list#index', as: 'general_shopping_list'

  resources :foods, except: [:index] do
    collection do
      get 'missing_foods'
    end
  end

  resources :inventories do
    resources :inventory_foods, only: [:index, :new, :create, :show, :update, :destroy]
  end  
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, foreign_key: 'users_id'
  has_many :inventory_foods, foreign_key: 'inventory_id'
  has_many :recipes, foreign_key: 'inventory_id'

  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods

  def total_quantity
    inventory_foods.sum(:quantity)
  end

  def total_price
    inventory_foods.sum { |inventory_food| inventory_food.food.price * inventory_food.quantity }
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[edit update destroy]

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user = current_user
    if @inventory.save
      redirect_to inventories_path(current_user), notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end

  def edit
    #  logic for edit
  end

  def update
    if @inventory.update(inventory_params)
      redirect_to @inventory, notice: 'Inventory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @inventory.destroy
    redirect_to inventories_url, notice: 'Inventory was successfully destroyed.'
  end

  private

  def validate_user
    return if @inventory && (current_user.id == @inventory.users_id || current_user.admin?)

    flash[:alert] = 'You do not have permission to delete this item.'
    redirect_back fallback_location: root_path
  end

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:name, :description, :users_id)
  end
end

app/views/inventories/edit.html.erb
<h1>Edit Inventory</h1>
<%= render 'form', inventory: @inventory %>

app/views/inventories/index.html.erb
<div class="container">
<div class="center">
<div class="head-section">
<h1>Inventories</h1>
<%= link_to 'Create New Inventory', new_inventory_path %>

<p> <%= link_to 'Back To Home', "/" %> </p>
</div>

<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>

<table class="table">
  <thead >
    <tr>
      <th>Inventory</th>
      <th>description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @inventories.each do |inventory| %>
          <tr>
        <td> <%= link_to inventory.name, inventory_inventory_foods_path(inventory) %> </td>
        <td><%= inventory.description %></td>
        <td>
        <%= link_to 'Remove item', inventory_path(inventory), method: :delete, data: { confirm: 'Are you sure you want to remove this item?' } %>
      </td>
              </tr>
    <% end %>
  </tbody>

</div>
</div>

app/views/inventories/new.html.erb
<div class="container" >
<div class="center" >


<h1 class="notice">New Inventory</h1>

<div class="Iform" >
<%= form_with(model: @inventory, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Inventory' %>
  </div>
  
  <%= link_to 'Back', inventories_path(current_user) %>
<% end %>

</div>

</div>
</div>

app/views/inventories/show.html.erb
<div class="container"> 
  <div class="center">

    <div class="heading">
      <h1 class="notice"><%= @inventory.name %> Shopping List</h1>
    </div> 

    <div class="mid-sec"> 
      <section>
        <span>Amount of food to buy : <%= @inventory.total_quantity %> </span>
      </section>

      <section>
      Recipe: <% @inventory.recipes.each do |recipe| %>
          <%= link_to recipe.name, recipe_path(recipe) %>
      <% end %>
      </section>

      <section>
        <span>Total Value Of Food Needed : $<%= @inventory.total_price %> </span>
      </section>

      <section>
        <span>Inventory: <%= link_to @inventory.name, inventories_path(@inventory) %></span>
      </section>
       
    </div>

    <!-- Inventory Foods -->
    <table class="table">
      <thead>
        <tr> 
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody> 
        <% @inventory.inventory_foods.each do |inventory_food| %> 
          <tr>
            <td><%= inventory_food.food.name %></td>
            <td><%= inventory_food.quantity %></td>
            <td> $ <%= inventory_food.food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>