config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    post 'associate_inventory', on: :member
  end

  resources :recipe_foods, only: [:index, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  root to: 'foods#index'
  get '/missing_foods', to: 'foods#missing_foods'
  get '/foods', to: 'foods#index', as: 'foods'

  get '/foods/:id', to: 'foods#show', as: 'food'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  get '/public_recipes', to: 'recipes#public_list', as: 'public_recipes'
  get '/GeneralShoppingList', to: 'general_shopping_list#index', as: 'general_shopping_list'

  resources :foods, except: [:index] do
    collection do
      get 'missing_foods'
    end
  end

  resources :inventories do
    resources :inventory_foods, only: [:index, :new, :create, :show, :update, :destroy]
  end  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :inventory, optional: true
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @public_recipes = Recipe.where(public: true).includes(recipe_foods: :food)

    if @public_recipes.present?
      @total_food_items = @public_recipes.sum { |recipe| recipe.recipe_foods.sum(:quantity) } || 0
      @total_price = @public_recipes.sum { |recipe| recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price } } || 0
    else
      @total_food_items = 0
      @total_price = 0
    end

    # Debug output
    puts "Total Food Items: #{@total_food_items}"
    puts "Total Price: #{@total_price}"
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @foods = @recipe.foods
    @inventories = Inventory.all
  end

  def associate_inventory
    @recipe = Recipe.find(params[:id])
    inventory_id = params[:inventory_id]

    if inventory_id.present?
      inventory = Inventory.find(inventory_id)
      @recipe.update(inventory:)
      redirect_to inventory_path(inventory), notice: 'Inventory generated successfully!'
    else
      redirect_to @recipe, alert: 'Please select an inventory.'
    end
  end

  def public_list
    @public_recipes = Recipe.includes(:foods).where(public: true).order(created_at: :desc)

    # Debug output
    puts "Debug - Public Recipes: #{@public_recipes.inspect}"

    if @public_recipes.present?
      @total_food_items = @public_recipes.sum { |recipe| recipe.recipe_foods.sum(:quantity) } || 0
      @total_price = @public_recipes.sum { |recipe| recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price } } || 0
    else
      @total_food_items = 0
      @total_price = 0
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="container">
  <div class="head-section">
    <h1 class="page-title">List of Recipes</h1>
    <%= link_to "New Recipe", new_recipe_path, class: "click-me" %>
  </div>

  

  <ul>
  <% if @public_recipes.empty? %>
    <li>No Recipes.</li>
  <% else %>
    <% @public_recipes.each do |recipe| %>
      <li>
        <%= link_to raw("#{recipe.name} <br> By: #{recipe.user.name}"), recipe_path(recipe), class: "recipe-name" %>
        <% if can? :destroy, recipe %>
          <%= button_to "Delete", recipe, method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "click-me" %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

</div>

app/views/recipes/new.html.erb
<div class="main-container">
  <div class="recipes-container">
    <h1 class="page-title">New Recipe</h1>
  </div>
  <%= form_with model: @recipe, url: recipes_path, class: 'form' do |form| %>
    <div class="field">
      <%= form.label :name, class: "name-label" %>
      <%= form.text_field :name, placeholder: "Name", class: "name-input", required: true %>
    </div>
    <div class="field">
      <%= form.label :preparation_time, class: "name-label" %>
      <%= form.number_field :preparation_time, placeholder: "Preparation Time", class: "name-input", required: true, step: '0.01' %>
    </div>
    <div class="field">
      <%= form.label :cooking_time, class: "name-label" %>
      <%= form.number_field :cooking_time, placeholder: "Cooking Time", class: "name-input", required: true, step: '0.01' %>
    </div>
    <div class="field">
      <%= form.label :public %>
      <%= form.check_box :public, class: "name-input" %>
    </div>
    <div class="field">
      <%= form.label :description, class: "name-label" %>
      <%= form.text_area :description, placeholder: "Description", class: "name-input", required: true %>
    </div>
    <div class="field">
      <%= form.submit "Create Recipe", class: "new-button" %> 
    </div>
  <% end %>
</div>

app/views/recipes/public_list.html.erb
<div class="container">
  <h1 class="head-section">Public Recipe List</h1>
  <ul class="recipes_list">
    <% @public_recipes.each do |recipe| %>
      <li>
       <div class="ft">
        <%= link_to raw("#{recipe.name} <br> By: #{recipe.user.name}"), recipe_path(recipe), class: "recipe-name" %>
         <span class="totalFood">
         <p>Total Food Items: <%= @total_food_items %></p>
         <p>Total Price: <%= number_to_currency(@total_price) %></p>
         </span>
         </div>

        <% if can? :destroy, recipe %>
          <%= button_to "Delete", recipe, method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "click-me" %>
        <% end %>
      </li>
    <% end %>
  </ul>

 

  <%= link_to 'Back to Recipes List', recipes_path, class: "btn btn-link" %>
</div>

app/views/recipes/show.html.erb
<button class="click-me"><%= link_to 'Back to Recipes List', recipes_path, class: "custom-link" %></button>
<h2 class='head-section recpTitle'><%= @recipe.name %></h2>

<div class='container'>
  <div class='indRecipeDetail'>
    <h3>Preparation time:  <%= @recipe.preparation_time %>hours </h3>
    <% if can? :destroy, @recipe %>
      <span class="public-btn">
        Public
        <%= check_box_tag 'recipe[public]', 1, @recipe.public, disabled: !can?(:destroy, @recipe) %>
      </span>
    <% end %>
  </div>
  

  <h3>Cooking time: <%= @recipe.cooking_time %> hours</h3>
  <p>Steps go here...</p>

  <div class="btnContainer">
    <button id="openPopup" class="btn btn-primary">Generate Shopping List</button>

    <% if can? :update, @recipe %>
    
        <label for="click" class="addIng click-me">Add Food</label>

    <% end %>
  </div>
  <hr>

   <%= render partial: 'common_features/addFood', locals: { recipe: @recipe } %>


<div class="bd" id="popup" style="display: none;">
  <h2>Generating Shopping List</h2>
  <%= form_tag associate_inventory_recipe_path(@recipe), method: :post do %>
    <p>Choose an inventory:</p>

    <% if @inventories.any? %>
      <%= select_tag 'inventory_id', options_for_select(@inventories.map { |inv| [inv.name, inv.id] }), include_blank: true %>
    <% else %>
    'no inventories found'
    <% end %>
    <%= submit_tag 'Generate Shopping List' %>
  <% end %>

  <button id="closePopup" class="close">&times;</button>
</div>


<script>
  $(document).ready(function() {
    $("#openPopup").click(function() {
      $("#popup").show();
    });

    $("#closePopup").click(function() {
      $("#popup").hide();
    });
  });
</script>