config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    post 'associate_inventory', on: :member
  end

  resources :recipe_foods, only: [:index, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  root to: 'foods#index'
  get '/missing_foods', to: 'foods#missing_foods'
  get '/foods', to: 'foods#index', as: 'foods'

  get '/foods/:id', to: 'foods#show', as: 'food'
  get '/generalshoppinglist', to: 'generalshoppinglist#index'
  get '/public_recipes', to: 'recipes#public_list', as: 'public_recipes'
  get '/GeneralShoppingList', to: 'general_shopping_list#index', as: 'general_shopping_list'

  resources :foods, except: [:index] do
    collection do
      get 'missing_foods'
    end
  end

  resources :inventories do
    resources :inventory_foods, only: [:index, :new, :create, :show, :update, :destroy]
  end  
end

app/views/common_features/_addFood.html.erb
 <input type="checkbox" id="click">
      
      <table class="table">
        <thead>
          <tr>
            <th>Food</th>
            <th>Measurement Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td><%= number_to_currency(food.price) %></td>
              <td><%= food.quantity %></td>
              <td>
                <% if current_user == food.user %>
                <%= link_to "Delete", food_path(food), data: { method: "delete", confirm: "Are you sure you want to delete #{food.name} from the database?" } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <!-- Modal Form -->
      <div class="content">
        <div class="header">
          <h2>Add Food</h2>
          <label for="click" class="fa-times">&times;</label>
        </div>

        <%= form_for(@food || Food.new, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
          <div class="form-group">
            <%= f.label :name, :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :name, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :measurement_unit, :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :measurement_unit, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :price, :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :quantity, :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :quantity, :class => "form-control" %>
            </div>
          </div>

          <div class="line"></div>

          <div class="foot-action">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "Add Food", :class => "btn btn-primary" %>
            </div>
            <label for="click" class="close-btn">Close</label>
          </div>
          
        <% end %>
      </div>

app/views/common_features/_add_form.html.erb
<%= form_for(food, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :measurement_unit, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :measurement_unit, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quantity, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :quantity, :class => "form-control" %>
    </div>
  </div>

  <div class="line"></div>

  <div class="foot-action">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Add Food", :class => "btn btn-primary" %>
    </div>
    <label for="click" class="close-btn">Close</label>
  </div>
<% end %>

app/views/common_features/_recipe.html.erb
<% if recipe %>
  <li class="recipes_list">
    <div class="recipe_detail">
      <h1 class="recipe-name">
        <%= link_to recipe.name, recipe  %>
      </h1>
      <p class="recipe-des"> <%= recipe.description %></p>
     
    </div>
    <div>
     <% if can? :destroy, recipe %>
        <%= button_to "Remove", recipe, method: :delete, data: { confirm: "Are you sure?" }, class: "new-button", form: { 'data-turbo-frame': '_top' } %>
      <% end %>
    </div>

  </li>
   
<% end %>